[package]
name = "thingbuf_hangup"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
# thingbuf = "0.1.4"
thingbuf = { path = "../../thingbuf" }
log = "0.4.21"
env_logger = "0.11.3"
